### ISSUE TITLE
Linux binary not working (Fedora Silverblue)

### ISSUE THREAD

**Issue by quazar-omega** [agmmnn/fineartdown#2]
I downloaded the latest linux build and ran it but I get an error when running it (regardless of the image):
```
$ ./fineartdown-linux https://fineartamerica.com/featured/johann-sebastian-bach-playing-the-organ-french-school.html
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: /tmp/pkg/2da0d9158a9def60f4ba14472c3cf85a226cd5fedab2a217742732778d95ef20/.pnpm/canvas@2.11.0/node_modules/canvas/build/Release/canvas.node: invalid ELF header
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/fineartdown/node_modules/.pnpm/canvas@2.11.0/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.5.0
[fabriziov@fedora Downloads]$ ./fineartdown-linux https://fineartamerica.com/featured/dancing-octopus-barathieu-gabriel.html
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: /tmp/pkg/2da0d9158a9def60f4ba14472c3cf85a226cd5fedab2a217742732778d95ef20/.pnpm/canvas@2.11.0/node_modules/canvas/build/Release/canvas.node: invalid ELF header
    at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/fineartdown/node_modules/.pnpm/canvas@2.11.0/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.5.0
```

The npm package worked like a charm, I love this so much!

**Comment by agmmnn** [comment]
Hey, thanks for feedback. I exactly dont know what is causing this problem but maybe

- The ‘canvas’ module has a number of system-level dependencies that must be installed on your system in order to work properly. https://github.com/Automattic/node-canvas/wiki/Installation:-Fedora-and-other-RPM-based-distributions#installing-dependencies
- It may be necessary to compile on linux. (using github actions)
- It could also be related to the pkg module.

**Comment by quazar-omega** [comment]
I see, all those sound possibile, I wonder if it could be packaged as an Appimage to (probably) avoid all those issues, it would be possibile to build it with GitHub Actions too
